# Generated by Django 3.0.5 on 2020-05-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20200503_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='MEDIA_ROOT/default.png', upload_to='', verbose_name='profile image'),
        ),
    ]
