# Generated by Django 3.0.5 on 2020-05-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='MEDIA_ROOT/default/default.png', upload_to='', verbose_name='profile image'),
        ),
    ]
