# Generated by Django 3.0.5 on 2020-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20200505_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='media/default/default.png', upload_to='', verbose_name='profile image'),
        ),
    ]
